version: '3'
services:
  mysql:
    image: mysql:8.0.28 #8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ekoiospw
      MYSQL_DATABASE: blogapi
      MYSQL_USER: ekoios
      MYSQL_PASSWORD: ekoiospw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    depends_on:
      - mysql
  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

networks:
  mysql:
    driver: bridge
 